#!/usr/bin/env python3
import argparse
from astropy.io import fits
import pyds9

parser = argparse.ArgumentParser()
parser.add_argument('files', nargs='+')
args = parser.parse_args()

ds9 = pyds9.DS9('ztf', wait=60)

ds9.set('cmap viridis')
ds9.set('zscale')

for i, f in enumerate(args.files):
    ds9.set('frame {}'.format(i + 1))
    with fits.open(f) as hdu:
        ext = 'diff' if 'diff' in hdu else 'sci'
        im = fits.HDUList()
        im.append(hdu[ext])
        ds9.set_pyfits(im)
