#!/usr/bin/env python3
# Licensed under a 3-clause BSD style license - see LICENSE.rst
import os
import argparse
from zchecker import ZStack, Config
from zchecker.cli_helpers import object_list

parser = argparse.ArgumentParser(
    description='Solar System target image stacker for ZChecker.')
parser.add_argument(
    'objects', type=object_list, nargs='?',
    help=('find and stack these targets, or those listed in this file'))
parser.add_argument(
    '--scale', default='both', choices=['coma', 'surface', 'both'],
    help='image scaling basis')
parser.add_argument(
    '--baseline', default=14, type=int,
    help='number of days to search for creating baseline image')
parser.add_argument(
    '--force', '-f', action='store_true',
    help='overwrite previous stacks')
parser.add_argument('--db', help='database file')
parser.add_argument('--log', help='log file')
parser.add_argument('--config', default=os.path.expanduser(
    '~/.config/zchecker.config'), help='configuration file')
parser.add_argument('-v', action='store_true', help='increase verbosity')

args = parser.parse_args()

assert args.scale in ['coma', 'surface', 'both']
if args.scale == 'both':
    scale_by = ['coma', 'surface']
else:
    scale_by = [args.scale]

config = Config.from_args(args)
with ZStack(config, save_log=True) as z:
    z.stack(scale_by, args.baseline, objects=args.objects,
            restack=args.force)
